### ISSUE TITLE
Wrong debug mode handling for User mode

### ISSUE THREAD

**Issue by tzwaenn** [openhwgroup/cv32e40s#242]
# Template for Bug Issue

### Component

**Component:RTL**

### Steps to Reproduce
See attached trace
![dret](https://user-images.githubusercontent.com/45827187/177099057-37c72a89-9756-4f28-8efa-5a7c97442637.png)
We see the core being set up for user mode, going to debug mode, and then executing a dret instruction. The dret violates the specification since it is supposed to restore the privilege from dcsr.prv which is not happening since dcsr.prv is Machine mode, but privilege level stays User mode. The RTL seems to try to set the privilege mode by assigning priv_lvl_n, but not priv_lvl_we, so the restore is not happening.
Incidentally, the trace also shows a previous issue: Upon entering debug mode, dcsr.prv is supposed to be set to the current privilege level (here User mode), but it is tied to Machine mode in RTL.

The issue was found with the OneSpin Processor Verification App, specifically the assertion verifying return behavior.

**Comment by Silabs-ArjanB** [comment]
additional ionfo from OneSpin: Saving the mode in dcsr.prv constantly stores PRIV_LVL_M in line 1498 and on a dret, prv_lvl_n is set as expected in line 1556, but not priv_lvl_we, so no level transition is happening.

**Comment by Silabs-ArjanB** [comment]
Both reported issue should be fixed with https://github.com/openhwgroup/cv32e40s/pull/260.

@tzwaenn Thank you very much for finding and reporting these issues (the user mode related additions to the debug circuitry were still work in progress, but it is great to see that OneSpin catches these issues). Could you please run OneSpin again and check if these issues have now properly been fixed?

**Comment by tzwaenn** [comment]
There is no longer a fail for the return assertion.

**Comment by Silabs-ArjanB** [comment]
@tzwaenn Could you please close this issue if you agree it has been fixed?
