### ISSUE TITLE
"pmpcfg" write not ignored

### ISSUE THREAD

**Issue by silabs-robin** [openhwgroup/cv32e40s#287]
**Component:RTL**: For issues in the RTL (e.g. for files in the rtl directory)

### Steps to Reproduce

1. 941c1b78, https://github.com/silabs-robin/core-v-verif/tree/pmp_assert
2. tcf_cvverif --rc=pmp_g3r3
3. a_cfgwdata_legal

### Problem

> When mseccfg.MML is set the system’s behavior changes in the following way:
> [...]
> Adding an M-mode-only or a locked Shared-Region rule with executable privileges is not possible and such pmpcfg writes are ignored, leaving pmpcfg unchanged
> -- smepmp

I don't think we follow the spec item quoted above.
See the _red_ highlighted signals in the trace below.

The trace shows an attempted cfg write, the pre-state, and the expected result.
Because MML=1 and RLB=0, shouldn't a write with L=1 and X=1 be ignored?
But still rvfi wdata shows that the csr is updated.

![image](https://user-images.githubusercontent.com/75431602/187192489-d26763c8-958a-4978-bf8a-0d4f10bd4ef2.png)

**Comment by Silabs-ArjanB** [comment]
Hi @silabs-oivind Isn't this the same as what was reported in https://github.com/openhwgroup/cv32e40s/issues/273 to not be an issue?

**Comment by silabs-oivind** [comment]
Hi @Silabs-ArjanB, @silabs-robin.
LRWX=1111 is a special case and is used to encode a shared, read-only readion (when mml=1):

From the smepmp spec:
"The encoding pmpcfg.LRWX=1111 can be used for sharing data between M-mode and S/U mode,
where both modes only have read-only access to the region. The rule remains locked so that any
further modifications to its associated configuration or address registers are ignored until a PMP
reset, unless mseccfg.RLB is set."

**Comment by silabs-robin** [comment]
> LRWX=1111 is a special case [...]

That is correct, and it was missing from the assert. After fixing this, the assertion detects no discrepancies between wdata and expectations.
